# Generated by Django 3.1.4 on 2021-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app19', '0002_employeeregistrationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
