# Generated by Django 3.1.4 on 2021-07-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
